#!/bin/bash
# tputcolors

post_install() {
  post_upgrade
}

post_upgrade() {
  update-desktop-database -q
  echo
  echo 'By using this package you accept the Steam license,'
  echo 'which has been installed in /usr/share/licenses/steam/LICENSE'
  echo 'If you do not accept this license, you must remove the package immediately.'
  echo
  echo 'Beware that some games need extra libraries, for more info please look our wiki page:'
  echo 'http://chakraos.org/wiki/index.php?title=Steam'
  echo
}
