post_install() {
  update-desktop-database -q
  gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
  echo "If you are running x86_64, you need the lib32 opt depends for your driver - check that mhwd has it correctly set"
  echo "If you are having problems with the steam license, remove .steam and .local/share/Steam"
  echo "Library issues can be fixed with the Steam (Purge Libraries) launcher"
  echo "Check https://forum.manjaro.org/index.php?topic=16054.msg149783 for info"
}

pre_install(){
  update-desktop-database -q
  gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
}

post_upgrade() {
  update-desktop-database -q
  gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
  echo "If you are running x86_64, you need the lib32 opt depends for your driver - check that mhwd has it correctly set"
  echo "If you are having problems with the steam license, remove .steam and .local/share/Steam"
  echo "Library issues can be fixed with the Steam (Purge Libraries) launcher"
  echo "Check https://forum.manjaro.org/index.php?topic=16054.msg149783 for info"
}

pre_upgrade(){
  update-desktop-database -q
  gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
}

post_remove() {
  update-desktop-database -q
  gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
}

